# Use the Node.js 20.17.0 base image
FROM node:20.17.0

# Set the working directory in the container
WORKDIR /app

# Copy the rest of the application code to the working directory
COPY . .

# Install dependencies
RUN npm install



# Expose the port that the service will run on
EXPOSE 3000

# Command to run the hello service
CMD ["node", "helloApp.js"]
