# Use the Node.js 20.17.0 base image
FROM node:20.17.0

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY . .

# Install dependencies
RUN npm install

# Expose the port that the service will run on
EXPOSE 3001

# Command to run the world service
CMD ["node", "worldApp.js"]
